### PR TITLE
open-telemetry-monitoring

### PR DESCRIPTION
**Pull request by omarsoufiane**
I created a monitoring using OpenTelemetry:
it's working using prometheus grafana and tempo.

I added a docker-compose file as an example that you can integrate into your existing docker-compose and then delete later.

## Release Notes

- **New Features**
  - Introduced a new Grafana dashboard for monitoring the "recy-api" with various performance metrics.
  - Added configuration for multiple monitoring services, including Prometheus, Tempo, and Loki, to enhance observability.
  - Integrated OpenTelemetry for improved monitoring and metrics collection in the application.

- **Bug Fixes**
  - Updated `.gitignore` to prevent tracking of specific monitoring-related directories.

- **Chores**
  - Added new dependencies for OpenTelemetry to enhance the project's observability capabilities.
  - Updated Docker Compose configuration to include multiple monitoring services.

[#128](https://github.com/detrash/recy-network/issues/128)

### CODE REVIEW

**Review by yurimutti — APPROVED** [review]

**Review by yurimutti — CHANGES_REQUESTED** [review]
We are working on a staging branch to refactor our backend, can you resolve those conflicts?

**Comment by yurimutti** [comment]
Please, consider resolving coderabbit comments.

**Review by omarsoufiane — COMMENTED** [review]
resolved conversations

**Review by yurimutti — APPROVED** [review]

**Comment by yurimutti** [comment]
> resolved conversations

Thanks for contributing!

**Pull request closed without merging**
